name: Check Terraform

on:
  push:
    paths:
      - "terraform/**/*.tf"
      - "terraform/**/*.tfvars"
      - ".github/workflows/check-terraform.yml"
  pull_request:
    paths:
      - "terraform/**/*.tf"
      - "terraform/**/*.tfvars"
      - ".github/workflows/check-terraform.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install mise and setup
        uses: jdx/mise-action@v3
        with:
          install: true
          install_args: "terraform"
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format Terraform
        run: task tf:fix

      - name: Commit and Push
        uses: 23prime/simple-commit-and-push@v1
        with:
          commit-message: "Auto format Terraform by `task tf:fix`"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Terraform
        run: task tf:fmt:check
