name: Check Terraform

on:
  push:
    paths:
      - "terraform/**/*.tf"
      - "terraform/**/*.tfvars"
      - ".github/workflows/check-terraform.yml"
  pull_request:
    paths:
      - "terraform/**/*.tf"
      - "terraform/**/*.tfvars"
      - ".github/workflows/check-terraform.yml"

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install mise and setup
        uses: jdx/mise-action@v3
        with:
          install: true
          install_args: "terraform"
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize Terraform (without backend)
        run: mise run tf-init-nobackend

      - name: Format Terraform
        run: mise run tf-fmt

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Auto fix by workflow"

      - name: Check Terraform
        run: mise run tf-check
